### ISSUE TITLE
[Feat] newPost 기본 UI 구현 ( drag & drop 외의 UI )

### ISSUE THREAD

**Issue by seongmin221** [CDS-Mobile1/CDS_iOS#15]
## 💡 Issue

newPost 관련 UI 에 관한 이슈 입니다 !
PR 을 조금 쪼개기 위해 drag & drop CollectionView 는 다른 이슈에서 진행하도록 하겠습니다 !

## 📝  Todo
- [ ] navigation bar UI
- [ ] collection view UI
- [ ] textview UI
- [ ] 하단 tableview UI
