### ISSUE TITLE
[Feat] 유용한 extension 추가

### ISSUE THREAD

**Issue by seongmin221** [CDS-Mobile1/CDS_iOS#16]
## 💡 Issue

쓸만한 extension 을 추가하려는 이슈입니다 !

## 📝  Todo
- [ ] UIViewController extension 추가
- [ ] UIView extension 추가
- [ ] 그 외가 있다면 추가 (?)
