### ISSUE TITLE
[Feat] 사랑쟝이 사용할 profile cell 만들기 ~

### ISSUE THREAD

**Issue by seongmin221** [CDS-Mobile1/CDS_iOS#18]
## 💡 Issue

저의 욕심으로 profile 에 gradient 를 넣게 되었는데요 하핳
그거 만드는 김에 profile view cell 들 만드는 이슈 입니닷 !

## 📝  Todo
- [ ] profile cell UI
- [ ] gradient 적용
- [ ] 사이즈 지정하도록 적용
- [ ] 상태에 따라 UI 변경하도록 enum 구성
