### ISSUE TITLE
[Feat] 스토리 View UI 구성

### ISSUE THREAD

**Issue by seongmin221** [CDS-Mobile1/CDS_iOS#22]
## 💡 Issue

스토리 View 의 UI 를 구성하는 Issue 입니다 !

## 📝  Todo
- [ ] 프로필 버튼 눌렀을 때 custom transition ( 가능하다면 ... )
- [ ] 전체적인 UI 구현
- [ ] 태그 버튼 누르면 태그한 사람 뜨는 modal 구성
- [ ] 좋아요 버튼 활성화
