### ISSUE TITLE
[Setting] CI/CD 적용

### ISSUE THREAD

**Issue by seongmin221** [CDS-Mobile1/CDS_iOS#3]
## 💡 Issue

원활한 작업을 위해 CI / CD 를 적용하고자 합니다 !
이를 위한 이슈 !

## 📝  Todo
- [ ] git - slack 연결
- [ ] git auto build
- [ ] git auto assign bot
